<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$dashletStrings['StockDashlet'] = array(
	'LBL_TITLE' => 'Bourse',
	'LBL_CONFIGURE_TITLE' => 'Titre:',
	'LBL_DESCRIPTION' => 'Affiche le cours des valeurs boursières sélectionnées',
	'LBL_SYMBOLS' => 'Symboles:',
	'LBL_DISPLAY_CHART' => 'Afficher le graphique:',
	'LBL_LAST_TRADE' => 'Dern. Cours',
	'LBL_DAYS_RANGE' => 'Var. Jour',
	'LBL_TRADE_TIME' => 'Heure',
	'LBL_52WK_RANGE' => 'Var. sur 1 an',
	'LBL_CHANGE' => 'Variation',
	'LBL_VOLUME' => 'Volume',
	'LBL_AVG_VOLUME' => 'Vol Moy (3m)',
	'LBL_PREV_CLOSE' => 'Clôture Préc.',
	'LBL_OPEN' => 'Ouverture',
	'LBL_MARKET_CAP' => 'Cap. Boursière',
	'LBL_BID' => 'Achat',
	'LBL_P_E' => 'PER (ttm)',
	'LBL_ASK' => 'Vente',
	'LBL_EPS' => 'BPA (ttm)',
	'LBL_1Y_TARGET_EST' => 'Objectif de prix',
	'LBL_DIV_YIELD' => 'Div &amp; Rendement',
	'LBL_SYMBOL' => 'Symbole',
	'LBL_PARSE_ERROR' => 'Erreur lors de la recherche.',
	
	'LBL_RANGE' => 'Variation sur: ',
	'LBL_1D' => '1j',
	'LBL_5D' => '5j',
	'LBL_3M' => '3m',
	'LBL_6M' => '6m',
	'LBL_1Y' => '1a',
	'LBL_2Y' => '2a',
	'LBL_5Y' => '5a',
	'LBL_TYPE' => 'Type: ',
	'LBL_BAR' => 'Barre',
	'LBL_LINE' => 'Courbe',
	'LBL_CANDLE' => 'Chandelier',
	'LBL_CLICK_FOR_LARGER' => 'Cliquer pour agrandir et obtenir davantage d\'options',
	'LBL_SCALE' => 'Echelle: ',
	'LBL_LINEAR' => 'Linéaire',
	'LBL_LOG' => 'Logarithmique',

	'LBL_ALL_USD' => 'Montants en Dollars US. Dern. mise à jour: {time}.',
	'LBL_VISIT_SITE' => 'Yahoo! Finance',
);
?> 
