<?php
if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');
// ajoutée
$dashletStrings['WeatherDashlet'] = array(
	'LBL_TITLE' => 'Météo',
	'LBL_CONFIGURE_TITLE' => 'Titre:',
	'LBL_DESCRIPTION' => 'Affiche la météo dans les villes sélectionnées',
	'LBL_CITY' => 'Ville',
	'LBL_WOEID' => 'Identifiant WOEID',
	'LBL_DEGREES_UNITS' => 'Unités:',
	'LBL_TODAY' => 'Aujourd\'hui (Max/Min)',
	'LBL_TOMORROW' => 'Demain',
	'LBL_CURRENT' => 'En ce moment',
	'LBL_CURRENT_CONDITIONS' => 'Conditions actuelles',
	'LBL_BAROMETER' => 'Pression',
	'LBL_HUMIDITY' => 'Humidité',
	'LBL_VISIBILITY' => 'Visibilité',
	'LBL_WIND' => 'Vent',
	'LBL_WIND_CHILL' => 'ressenti avec le vent',
	'LBL_SUNRISE' => 'Lever',
	'LBL_SUNSET' => 'Coucher',
	'LBL_FORECAST' => 'Prévisions',
	'LBL_HIGH' => 'Max',
	'LBL_LOW' => 'Min',
	'LBL_UNLIMITED' => 'Illimité',
	'LBL_AND' => 'et',
	'LBL_PRESSURE_STEADY' => 'stable',
	'LBL_PRESSURE_RISING' => 'en hausse rapide',
	'LBL_PRESSURE_FALLING' => 'en baisse rapide',
	'LBL_CURRENT_CITIES' => 'Villes actuelles:',
	'LBL_ADD_CITY' => 'Ajouter une ville',
	'LBL_DISPLAY_TIME' => 'Afficher l\'heure locale:',
	'LBL_LIST_TIME' => 'Heure',
	'LBL_CLEAR' => 'Réinitialiser',
	'LBL_SEARCH' => 'Rechercher',
	'LBL_REMOVE' => 'Supprimer',
	
	'LBL_WIND_DEG0' => 'N',
	'LBL_WIND_DEG45' => 'NE',
	'LBL_WIND_DEG90' => 'E',
	'LBL_WIND_DEG135' => 'SE',
	'LBL_WIND_DEG180' => 'S',
	'LBL_WIND_DEG225' => 'SO',
	'LBL_WIND_DEG270' => 'O',
	'LBL_WIND_DEG315' => 'NO',
	
	'LBL_LAST_UPDATE' => 'Dern. mise à jour: {time}.',
	'LBL_VISIT_SITE' => 'Yahoo! Weather',
	
	'LBL_LOOKUP_ERROR' => 'Une erreur s\'est produite pendant la recherche',
);
?> 